name: caraqueprod
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  

  cupertino_icons: ^1.0.2
  flutter_flavor: ^3.1.1
  flutter_flavorizr: ^2.2.3
  firebase_core: ^2.4.1
  cloud_firestore: ^4.7.0
  freezed_annotation: ^2.2.0 
  get: ^4.6.5
  fluttertoast: ^8.1.2 
  firebase_auth: ^4.10.1
  firebase_remote_config: ^4.2.4
  flutter_dotenv: ^5.0.2
  google_fonts: ^6.2.1
  lottie: ^3.1.2 #アニメーション
  carousel_slider: ^4.0.0 #スライダー
  smooth_page_indicator: ^0.3.0-nullsafety.0 #スライダーの丸
  flutter_staggered_animations: ^1.1.1 #ウィジェットアニメーション






dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  build_runner: ^2.3.3 #freezed_annotation
  freezed: ^2.3.2 #freezed_annotation
  json_serializable: ^6.6.1  #freezed_annotation

flutter:
  uses-material-design: true
  assets:
    - assets/lotties/
    - assets/images/

  fonts:
    - family: Mincho
      fonts:
        - asset: fonts/SawarabiMincho-Regular.ttf






flavorizr:
  app:
    android:
      flavorDimensions: "flavor-type"
  flavors:
    dev:
      app:
        name: "CaraqueDev"
      android:
        applicationId: "com.firebaseapp.caraquedev"
      ios:
        bundleId: "com.firebaseapp.caraquedev"
    prod:
      app:
        name: "Caraque"
      android:
        applicationId: "com.firebaseapp.caraqueprod"
      ios:
        bundleId: "com.firebaseapp.caraqueprod"
 